export const UPLOADED_FILES_UPDATE = 'UPLOADED_FILES_UPDATE'
export const UPLOADED_FILES_RESET = 'UPLOADED_FILES_RESET'

export const SELECTED_FILES_UPDATE = 'SELECTED_FILES_UPDATE'
export const SELECTED_FILES_RESET = 'SELECTED_FILES_RESET'

export const MESSAGE_UPDATE = 'MESSAGE_VISIBLE_UPDATE'
export const MESSAGE_RESET = 'MESSAGE_VISIBLE_RESET'

export const LOAD_UPDATE = 'LOAD_UPDATE'
export const LOAD_RESET = 'LOAD_RESET'